### PR TITLE
Login using Selenium (very rough but works)

### PR DESCRIPTION
**Pull request by aaronjamt**
When running this script, it will now open a browser window using Selenium and allow the user to log in to the actual Floatplane website. It's very rough code (I haven't done any Go programming before, at least that I remember), minimally commented, and doesn't save your session (you have to log in and enter your 2FA code, if you have one, every single time), but it works.

### CODE REVIEW

**Comment by aaronjamt** [comment]
Update: I found a Go module to save credentials to a user's keyring so now it will do so whenever possible (and try to retrieve from the keyring first before prompting the user to log in)

**Comment by Flonja** [comment]
I like the keyring solution that you contributed, but relying on Selenium is something I'm not willing to put in a library. Selenium seems to have extra (native?) dependencies that just added extra bloat. Proper (frontend) authentication should probably be handled outside of this project.

**Comment by aaronjamt** [comment]
How about a copy+paste Javascript command you could enter into the developer console to grab the SID?

**Comment by Flonja** [comment]
I have put your pr in another [repository](https://github.com/Flonja/planeauth). Please look there how I would have implemented your idea

**Comment by aaronjamt** [comment]
All that needs to be done for this repo then is adding integration with the other one somehow so I'll close this issue since that's a broader topic.

**Pull request closed without merging**
